# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
# ... other parts of the file ...

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build: # Add this jobs section
      - | # Use a multi-line string for multiple commands
        echo "--- Debugging Environment ---"
        echo "sys.path before Sphinx build:"
        python -c "import sys; print(sys.path)"
        echo "PYTHONPATH environment variable:"
        echo $PYTHONPATH
        echo "Attempting to import nucleardatapy before Sphinx build:"
        # Simplified import check - will print '0' for success, '1' for failure
        python -c "import sys; try: import nucleardatapy; sys.exit(0) except ImportError: sys.exit(1)" && echo "nucleardatapy import successful" || echo "nucleardatapy import failed"

        echo "Attempting to import matplotlib before Sphinx build:"
        # Simplified import check - will print '0' for success, '1' for failure
        python -c "import sys; try: import matplotlib; sys.exit(0) except ImportError: sys.exit(1)" && echo "matplotlib import successful" || echo "matplotlib import failed"

        echo "--- End Debugging Environment ---"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally, but recommended,
# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    # Install your project package from the repository root
    - method: pip
      path: .

    # Install documentation-specific requirements from a separate file
    - requirements: docs/requirements.txt

  # If your main project requirements are separate and needed for docs runtime:
  # - requirements: requirements.txt
