title: Nuclear data toolkit
author: J. Margueron, et al.
copyright: "2025"
logo: logo.png
repository:
  url: https://github.com/jeromemargueron/nucleardatapy
  path_to_book: book/ # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)
execute:
  execute_notebooks: force
  timeout: -1

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# html options
html:
  use_repository_button: true # Whether to add a link to your repository button
  use_issues_button: true # Whether to add an "open an issue" button
  home_page_in_navbar: true # Whether to have the home page in the side bar

launch_buttons:
  notebook_interface: "jupyterlab" # or "classic"
  colab_url: "https://colab.research.google.com" # Adding Colab launch option

# disable building anything not included in the TOC
only_build_toc_files: true
