name: Build & publish Jupyter Book

env:
  CLONE_PATH: ${{ github.workspace }}
  EXAMPLES_BOOK: ${{ github.workspace }}/book/_build/html

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tox and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build Jupyter Book using tox
        run: |
          pushd $CLONE_PATH
          tox -e book
          popd

      - name: Upload Jupyter Book artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.EXAMPLES_BOOK }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
