name: Build Jupyter Book (tox-based)

env:
  CLONE_PATH: ${{ github.workspace }}
  EXAMPLES_BOOK: ${{ github.workspace }}/book/_build/html

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install OpenMPI
        run: |
          sudo apt-get update
          sudo apt-get install -y openmpi-bin

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build Jupyter Book via tox
        run: |
          pushd $CLONE_PATH
          tox -r -e book
          popd

      - name: Archive examples Jupyter book
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.EXAMPLES_BOOK }}

      - name: Deploy Jupyter Book
        id: deployment
        uses: actions/deploy-pages@v2
